name: Shell Commands

on:
 push:
    branches:
      - master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: before checkout
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: master
      - name: after checkout
        run: |
          pwd
          ls -a
      - name: file replace
        uses: falnyr/replace-env-vars-action@master
        env:
          FOO: hola
          BAR: haloo
        with:
          filename: test.txt
      - name: after replace
        run: cat test.txt