name: Shell Commands

on:
  push:
    branches:
      - master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: before checkout
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v2.0.0
      - name: after checkout
        run: |
          pwd
          ls -a