name: Shell Commands

on:
 pull_request:
    branches:
      - master
    types: [closed]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: before checkout
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: master
      - name: after checkout
        run: |
          pwd
          ls -a