name: Shell Commands

on:
  pull_request:
    types: [closed]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: multiline script
        run: |
          pwd
          ls
          node -v
          npm -v
          composer -v